require 'rails_helper'
require_relative '../../../lib/mdl/cite_details.rb'

describe MDL::CiteDetails do
  let(:solr_doc) do
   JSON.parse(File.read(Rails.root.join('spec', 'fixtures', 'solr_doc.json')))
  end
  subject { MDL::CiteDetails.new(solr_doc: solr_doc) }
  it 'transforms from solr to react-citation details' do
    expect(subject.to_hash).to eq({:focus=>true, :type=>"details", :label=>"Details", :fields => [{:label=>"Title", :field_values=>[{:text=>"Aeromagnetic map of Minnesota, central region, Plate 1"}]}, {:label=>"Creator", :delimiter=>", ", :field_values=>[{:text=>"Chandler, Val W.", :url=>"/?f[creator_ssim][]=Chandler,%20Val%20W."}]}, {:label=>"Date", :field_values=>[{:text=>"1985"}]}, {:label=>"Description", :field_values=>[{:text=>"Total magnetic intensity anomaly (relative to the earth's magnetic field), color coded, scale 1:250,000.  Interpretation of magnetic data collected from airborne surveys, the map colors indicate the distribution and concentration of magnetic minerals (primarily iron-bearing) within the upper crust of the earth. Electronic file available at: ftp://mgssun6.mngs.umn.edu/map_catalog/pdf/umn21100.pdf"}]}, {:label=>"Contributing Organization", :field_values=>[{:text=>"Minnesota Geological Survey", :url=>"/?f[contributing_organization_ssi][]=Minnesota%20Geological%20Survey"}]}, {:label=>"Type", :field_values=>[{:text=>"Cartographic", :url=>"/?f[type_ssi][]=Cartographic"}]}, {:label=>"Format", :field_values=>[{:text=>"Maps", :url=>"/?f[physical_format_ssi][]=Maps"}]}, {:label=>"Publishing Agency", :field_values=>[{:text=>"Minnesota Geological Survey", :url=>"/?f[publishing_agency_ssi][]=Minnesota%20Geological%20Survey"}]}, {:label=>"Dimensions", :field_values=>[{:text=>"64 x 93", :url=>"/?f[dimensions_ssi][]=64%20x%2093"}]}, {:label=>"Country", :field_values=>[{:text=>"United States", :url=>"/?f[country_ssi][]=United%20States"}]}, {:label=>"State", :field_values=>[{:text=>"Minnesota", :url=>"/?f[state_ssi][]=Minnesota"}]}, {:label=>"District", :field_values=>[{:text=>"central region", :url=>"/?f[district_ssi][]=central%20region"}]}, {:label=>"Language", :field_values=>[{:text=>"English"}]}, {:label=>"Rights", :field_values=>[{:text=>"Public domain.  We request that if the images are used credit be given to the Minnesota Geological Survey, University of Minnesota."}]}, {:label=>"Local Identifier", :field_values=>[{:text=>"a5 Pl1"}]}, {:label=>"MDL Identifier", :field_values=>[{:text=>"umn96127"}]}, {:label=>"Contact information", :field_values=>[{:text=>"Minnesota Geological Survey, 2642 University Avenue, St. Paul, MN 55114"}]}, {:label=>"Fiscal Sponsor", :field_values=>[{:text=>"Grant provided to the Minnesota Digital Library Coalition through the Library Services and Technology Act (LSTA) and the State Library Services and School Technology unit of the Minnesota Department of Education"}]}]})
  end
end
